### ISSUE TITLE
Add support for building on Aarch64

### ISSUE THREAD

**Issue by jerboaa** [AdoptOpenJDK/openjdk8-upstream-binaries#10]
With 8u292-b01 the [Aarch64 JIT port](https://bugs.openjdk.java.net/browse/JDK-8257192) has been integrated into JDK 8u mainline. We should add support for building on Aarch64 in our build scripts and publish EA builds for them on Linux.

**Comment by jerboaa** [comment]
@jhuttana Please take a look when you get a chance.

**Comment by jhuttana** [comment]
Sure

**Comment by karianna** [comment]
> With 8u292-b01 the [Aarch64 JIT port](https://bugs.openjdk.java.net/browse/JDK-8257192) has been integrated into JDK 8u mainline. We should add support for building on Aarch64 in our build scripts and publish EA builds for them on Linux.

Does this mean the special shenandoah-aarch64 jdk8u forest/port will eventually go away?

**Comment by sxa** [comment]
> > With 8u292-b01 the [Aarch64 JIT port](https://bugs.openjdk.java.net/browse/JDK-8257192) has been integrated into JDK 8u mainline. We should add support for building on Aarch64 in our build scripts and publish EA builds for them on Linux.
> 
> Does this mean the special shenandoah-aarch64 jdk8u forest/port will eventually go away?

@karianna No I don't expect so - the aarch64 support is going in but NOT Shenandoah so I expect that to continue. The question for AdoptOpenJDK is whether we want to switch or stuck with the branch we have and retain functionality (I'm assuming we have it enabled in our builds from that branch...I told someone recently that we did!), or switch to mainline and not have the Shenandoah support.

**Comment by karianna** [comment]
Tough call - I bet we only have a small handful of Shenandoah 8 users, but
we may be the only option they have?

Cheers,
Martijn

**Comment by jerboaa** [comment]
> > With 8u292-b01 the [Aarch64 JIT port](https://bugs.openjdk.java.net/browse/JDK-8257192) has been integrated into JDK 8u mainline. We should add support for building on Aarch64 in our build scripts and publish EA builds for them on Linux.
> 
> Does this mean the special shenandoah-aarch64 jdk8u forest/port will eventually go away?

@karianna Yes, it'll likely be retired in favor of https://hg.openjdk.java.net/shenandoah/jdk8. It doesn't make sense to keep it in the aarch64 space. The trees would be identical anyway. Previously shenandoah/jdk8 didn't have aarch64 support, but with it now upstream that changed. We'll keep folks in the loop and announce accordingly if that happens.

**Comment by jerboaa** [comment]
> > > With 8u292-b01 the [Aarch64 JIT port](https://bugs.openjdk.java.net/browse/JDK-8257192) has been integrated into JDK 8u mainline. We should add support for building on Aarch64 in our build scripts and publish EA builds for them on Linux.
> > 
> > 
> > Does this mean the special shenandoah-aarch64 jdk8u forest/port will eventually go away?
> 
> @karianna No I don't expect so - the aarch64 support is going in but NOT Shenandoah so I expect that to continue. The question for AdoptOpenJDK is whether we want to switch or stuck with the branch we have and retain functionality (I'm assuming we have it enabled in our builds from that branch...I told someone recently that we did!), or switch to mainline and not have the Shenandoah support.

If Shenandoah support is desired for aarch64 JDK 8 builds of adopt, then the mirror job will likely have to change to the new location. I'll keep you posted.
