### ISSUE TITLE
Move to git mirrors for builds

### ISSUE THREAD

**Issue by jerboaa** [AdoptOpenJDK/openjdk8-upstream-binaries#13]
https://mail.openjdk.java.net/pipermail/jdk8u-dev/2021-December/014457.html announced JDK 8u's conversion to a mono-repository with a live git mirror. At this point it should be doable to produce upstream builds from git mirrors. We should switch to building from git mirrors by the time we do 8u332 EA builds (post January).

**Comment by jerboaa** [comment]
@stooke FYI.

**Comment by jerboaa** [comment]
Relevant git mirror for EA builds: https://github.com/openjdk/jdk8u

**Comment by stooke** [comment]
Wouldn't the EA build repo be jdk8u-dev?

**Comment by jerboaa** [comment]
> Wouldn't the EA build repo be jdk8u-dev?

No. `openjdk/jdk8u` has the promotions and the tags. Similar to why we were building from `jdk8u/jdk8u` in mercurial.

**Comment by jerboaa** [comment]
On second thought, we need to move to a monorepo ASAP. There won't be a `8u322-b05` (next EA promotion) from the old forest which our scripts are currently using. So best to bite the bullet now and build from the git mirror.

**Comment by jhuttana** [comment]
> https://mail.openjdk.java.net/pipermail/jdk8u-dev/2021-December/014457.html announced JDK 8u's conversion to a mono-repository with a live git mirror. At this point it should be doable to produce upstream builds from git mirrors. We should switch to building from git mirrors by the time we do 8u332 EA builds (post January).

Sure. Thank you!

**Comment by jerboaa** [comment]
@jhuttana See the comment above. Please move to git ASAP.

**Comment by jhuttana** [comment]
> @jhuttana See the comment above. Please move to git ASAP.

Okay I will make the changes -> verify and raise a PR ASAP :)

**Comment by jerboaa** [comment]
Reopening as we need windows support.

**Comment by jhuttana** [comment]
> Reopening as we need windows support.

Yes :) sorry I had linked the issue with PR.
Thank you!

**Comment by jerboaa** [comment]
No worries!
