### ISSUE TITLE
ARM32/Raspberry Pi Build for 8u242?

### ISSUE THREAD

**Issue by justinyunke** [AdoptOpenJDK/openjdk8-upstream-binaries#2]
Hi --

  The current AdoptOpenJDK arm release for 8u232 is unusable on the Raspberry Pi, causing a CPU 100% issue similar to that documented here:  https://github.com/AdoptOpenJDK/openjdk-build/issues/1287

  The daily build (8u252 series) does not experience this issue.

  Can we see an 8u24x release?

-- Justin

**Comment by jerboaa** [comment]
@justinyunke Please open an issue about this in https://github.com/AdoptOpenJDK/openjdk-build/issues This repository is about upstream OpenJDK 8u (Project builds). As far as I know people are working on builds for aarch64 and aarch32 for the 8u242 update.

**Comment by jerboaa** [comment]
Note that we don't have intentions to produce arm 32 bit builds for OpenJDK Project Builds. Anybody is welcome to build their own or use AdoptOpenJDK binaries, or yet better, help AdoptOpenJDK produce those builds arm 32 builds on the build farm.

**Comment by jerboaa** [comment]
Project builds available via:
https://adoptopenjdk.net/upstream.html

... are Linux/Windows x86_64 only.
